### PR TITLE
Suggestion for endpoints

### PR DESCRIPTION
**Pull request by vvmnnnkv**
A suggestion for endpoints (#3) :-)

```
const hf = new HfInference('your api key');
const gpt2 = hf.endpoint('https://xyz.eu-west-1.aws.endpoints.huggingface.cloud/gpt2');
const { generated_text } = await gpt2.textGeneration({inputs: 'The answer to the universe is'});
```

### CODE REVIEW

**Comment by coyotte508** [comment]
:exploding_head:

**Review by coyotte508 — COMMENTED** [review]
Nice! I added some docs

cc @philschmid , @Michellehbn , @TimMikeladze 

Since it's a big feature, waiting some time for people to comment if needed before the API is set in stone ;)

**Review by julien-c — COMMENTED** [review]
looks really nice!

**Comment by Grsmto** [comment]
I might be missing something but with this API you could technically do the following:

```js
const gpt2 = hf.endpoint('https://xyz.eu-west-1.aws.endpoints.huggingface.cloud/gpt2');
await gpt2.textGeneration({ model: 'some-other/model', inputs: 'The answer to the universe is' });
```

So what would happen in that case?

**Comment by coyotte508** [comment]
> I might be missing something but with this API you could technically do the following:
> 
> ```js
> const gpt2 = hf.endpoint('https://xyz.eu-west-1.aws.endpoints.huggingface.cloud/gpt2');
> await gpt2.textGeneration({ model: 'some-other/model', inputs: 'The answer to the universe is' });
> ```
> 
> So what would happen in that case?

Hmm yes typing should be improved

**Comment by coyotte508** [comment]
Merging :fire: 

I created another issue: #146 to address the typings before [Inference 2.0](https://github.com/huggingface/huggingface.js/milestone/1) @Grsmto

**Comment by julien-c** [comment]
let's do some comms around this feature 🔥

**Pull request merged**
