### PR TITLE
Add grok as lib for download stats

### PR DESCRIPTION
**Pull request by osanseviero**

### CODE REVIEW

**Review by SBrandeis — APPROVED** [review]

**Review by julien-c — COMMENTED** [review]
maybe name it grok to be more future proof?

**Comment by osanseviero** [comment]
I named it based in the GH repo https://github.com/xai-org/grok-1, i think being consistent with there makes sense, but no strong opinion

**Comment by julien-c** [comment]
i think it's slightly better to name it grok but no strong opinion either

**Review by pcuenca — APPROVED** [review]
Very cool!

**Review by julien-c — APPROVED** [review]

**Review by Wauplin — APPROVED** [review]

**Review by JioCreators — APPROVED** [review]

**Pull request merged**
