### PR TITLE
Allow single input for generation endpoint

### PR DESCRIPTION
**Pull request by 28Smiles**
According to spec inputs can be either a single `string` or a `string` array, with the result beeing either a single `TextGenerationOutput` or and array of them.

### CODE REVIEW

**Comment by coyotte508** [comment]
Hello, your PR changes the  output type but your PR title mentions the input type, is it intended?

**Comment by 28Smiles** [comment]
The output type is inputtype dependent, therefore yes. If a single input is provided to tgi it will result in an single output, multiple inputs will result in multiple outputs. Therefore a change handling a single output, will allow a single input to work.

**Comment by coyotte508** [comment]
@Wauplin how does the python lib handle this? :pray:

**Comment by 28Smiles** [comment]
https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/inference/_client.py#L1876

**Review by coyotte508 — APPROVED** [review]
Thanks @28Smiles !

Will still wait a bit for other inputs before merging

**Comment by 28Smiles** [comment]
> Thanks @28Smiles !
> 
> Will still wait a bit for other inputs before merging

While further investigating https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/inference/_client.py#L2197 also throws an exception if tgi returns a single object, which seems odd. Intriguingly, it was implemented like this from the get-go either its my older tgi version (v1.4.3). I am currently stuck on this tgi version and can't test newer versions.

**Comment by Wauplin** [comment]
Although TGI/InferenceAPI support batched requests, the Python client [does not implement that](https://github.com/huggingface/huggingface_hub/blob/05fdb7633fe5e51c570115860ce552f20661c3ba/src/huggingface_hub/inference/_client.py#L1878). The [inference specs](https://github.com/huggingface/huggingface.js/blob/8cba743ba29c86765d1ff840c1b0172de8bb981b/packages/tasks/src/tasks/text-generation/spec/input.json#L10) also does not allow array as input. The main reason is not technical but to avoid inconsistencies in the API + potentially block us in the future if we want to add a feature that breaks the batched requests. In any case, TGI is already batching requests server-side so looping over your inputs client-side should not be causing much delay. You only lose the extra HTTP overhead but we consider it as neglictable compared to the time it takes to generate tokens.

**Comment by 28Smiles** [comment]
> Although TGI/InferenceAPI support batched requests, the Python client [does not implement that](https://github.com/huggingface/huggingface_hub/blob/05fdb7633fe5e51c570115860ce552f20661c3ba/src/huggingface_hub/inference/_client.py#L1878). The [inference specs](https://github.com/huggingface/huggingface.js/blob/8cba743ba29c86765d1ff840c1b0172de8bb981b/packages/tasks/src/tasks/text-generation/spec/input.json#L10) also does not allow array as input. The main reason is not technical but to avoid inconsistencies in the API + potentially block us in the future if we want to add a feature that breaks the batched requests. In any case, TGI is already batching requests server-side so looping over your inputs client-side should not be causing much delay. You only lose the extra HTTP overhead but we consider it as neglictable compared to the time it takes to generate tokens.
> 
> I would therefore not proceed with this PR, at least short-term. cc @SBrandeis @osanseviero

This pr is not handling batched requests, its handling single return objects, cause tgi (at least in my version, can’t verify for others), is returning a single object instead of an array of length 1

**Comment by 28Smiles** [comment]
I can also verify this for tgi v2.1.1 now.
```
curl -X 'POST' \
  'http://10.11.0.5:8000/generate' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "inputs": "My name is Olivier and I"
}'
```
Response:
```
{
  "generated_text": " am from Belgium. I've been playing classical guitar for almost 5 years and I am now gaining interest in Flamenco guitar. I want to take lessons in a traditional flamenco way for 3 to 6 months with a good master in Barcelona but I don't know how to get started. Could you have some recommendations about how to approach this? Maybe websites, contact details of good masters, schools, etc. I've tried contacting the 'Amics"
}
```

This is not an array.

**Comment by 28Smiles** [comment]
> Thanks for the PR and explanation @28Smiles! We double-checked internally and this change is indeed necessary to ensure consistent behavior.

Should I quickly add a pr to the python client for you aswell?

**Comment by Wauplin** [comment]
Thanks for opening it on the Python side as well!

**Comment by 28Smiles** [comment]
> Thanks for opening it on the Python side as well!

I am glad to be helpful

**Pull request merged**
