### PR TITLE
:bug: Jinja - treat `none` as `null` instead of a variable name

### PR DESCRIPTION
**Pull request by giladgd**
I encountered the issue where when a Jinja template sets a variable to `none`, it treats it as a variable name and sets its value to `undefined`, and then checking that the variable value is not `none` fails.

Given this template:
```
{%- if not null_val is defined -%}
    {%- set null_val = none -%}
{%- endif -%}
{%- if null_val is not none -%}
    {{- 'fail' -}}
{%- else -%}
    {{- 'pass' -}}
{%- endif -%}
```

The current code will set `null_val` to `undefined`, then `null_val is not none` will be interpreted as `true` (since `undefined !== null`), and thus it'll render "fail".

This PR fixes that by interpreting a variable named `none` as a `NullValue`, since `none` should be a reserved keyword.

### CODE REVIEW

**Review by Vaibhavs10 — COMMENTED** [review]
Thanks for the PR @giladgd - pinging @xenova for review.

cc: @Rocketknight1 for vis too.

**Review by xenova — CHANGES_REQUESTED** [review]
Thanks for the PR! You followed the format perfectly and the tests too 👍 
Maybe a better way to handle `none` would be to handle it like `true` and `false`, as done here:

https://github.com/huggingface/huggingface.js/blob/a5726aca189de94988980731cf53e87ea65d7b76/packages/jinja/src/lexer.ts#L73-L82

**Comment by giladgd** [comment]
@xenova I've updated the PR to treat `null` as a literal

**Comment by xenova** [comment]
PR looks great - running unit tests and will merge soon! 🤞

**Review by xenova — APPROVED** [review]
LGTM! Tests pass now (just had to update all "none" to be `NullLiteral`)

**Comment by xenova** [comment]
On that note, do you have a chat template which uses `none`? Would be nice to add an end-to-end unit test.

**Comment by giladgd** [comment]
Sorry for the late response, got a bit sidetracked.
I've encountered some Llama 3.1 chat templates that use it. Here's one of them:
<details>
    <summary>Template</summary>

```jinja
{{- bos_token }}
{%- if custom_tools is defined %}
    {%- set tools = custom_tools %}
{%- endif %}
{%- if not tools_in_user_message is defined %}
    {%- set tools_in_user_message = true %}
{%- endif %}
{%- if not date_string is defined %}
    {%- set date_string = "26 Jul 2024" %}
{%- endif %}
{%- if not tools is defined %}
    {%- set tools = none %}
{%- endif %}

{#- This block extracts the system message, so we can slot it into the right place. #}
{%- if messages[0]['role'] == 'system' %}
    {%- set system_message = messages[0]['content']|trim %}
    {%- set messages = messages[1:] %}
{%- else %}
    {%- set system_message = "" %}
{%- endif %}

{#- System message + builtin tools #}
{{- "<|start_header_id|>system<|end_header_id|>\n\n" }}
{%- if builtin_tools is defined or tools is not none %}
    {{- "Environment: ipython\n" }}
{%- endif %}
{%- if builtin_tools is defined %}
    {{- "Tools: " + builtin_tools | reject('equalto', 'code_interpreter') | join(", ") + "\n\n"}}
{%- endif %}
{{- "Cutting Knowledge Date: December 2023\n" }}
{{- "Today Date: " + date_string + "\n\n" }}
{%- if tools is not none and not tools_in_user_message %}
    {{- "You have access to the following functions. To call a function, please respond with JSON for a function call." }}
    {{- 'Respond in the format {"name": function name, "parameters": dictionary of argument name and its value}.' }}
    {{- "Do not use variables.\n\n" }}
    {%- for t in tools %}
        {{- t | tojson(indent=4) }}
        {{- "\n\n" }}
    {%- endfor %}
{%- endif %}
{{- system_message }}
{{- eot_token }}

{#- Custom tools are passed in a user message with some extra guidance #}
{%- if tools_in_user_message and not tools is none %}
    {#- Extract the first user message so we can plug it in here #}
    {%- if messages | length != 0 %}
        {%- set first_user_message = messages[0]['content']|trim %}
        {%- set messages = messages[1:] %}
    {%- else %}
        {{- raise_exception("Cannot put tools in the first user message when there's no first user message!") }}
{%- endif %}
    {{- '<|start_header_id|>user<|end_header_id|>\n\n' -}}
    {{- "Given the following functions, please respond with a JSON for a function call " }}
    {{- "with its proper arguments that best answers the given prompt.\n\n" }}
    {{- 'Respond in the format {"name": function name, "parameters": dictionary of argument name and its value}.' }}
    {{- "Do not use variables.\n\n" }}
    {%- for t in tools %}
        {{- t | tojson(indent=4) }}
        {{- "\n\n" }}
    {%- endfor %}
    {{- first_user_message + eot_token}}
{%- endif %}

{%- for message in messages %}
    {%- if not (message.role == 'ipython' or message.role == 'tool' or 'tool_calls' in message) %}
        {{- '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + eot_token }}
    {%- elif 'tool_calls' in message %}
        {%- if not message.tool_calls|length == 1 %}
            {{- raise_exception("This model only supports single tool-calls at once!") }}
        {%- endif %}
        {%- set tool_call = message.tool_calls[0].function %}
        {%- if builtin_tools is defined and tool_call.name in builtin_tools %}
            {{- '<|start_header_id|>assistant<|end_header_id|>\n\n' -}}
            {{- "<|python_tag|>" + tool_call.name + ".call(" }}
            {%- for arg_name, arg_val in tool_call.arguments | items %}
                {{- arg_name + '="' + arg_val + '"' }}
                {%- if not loop.last %}
                    {{- ", " }}
                {%- endif %}
                {%- endfor %}
            {{- ")" }}
        {%- else  %}
            {{- '<|start_header_id|>assistant<|end_header_id|>\n\n' -}}
            {{- '{"name": "' + tool_call.name + '", ' }}
            {{- '"parameters": ' }}
            {{- tool_call.arguments | tojson }}
            {{- "}" }}
        {%- endif %}
        {%- if builtin_tools is defined %}
            {#- This means we're in ipython mode #}
            {{- "<|eom_id|>" }}
        {%- else %}
            {{- eot_token }}
        {%- endif %}
    {%- elif message.role == "tool" or message.role == "ipython" %}
        {{- "<|start_header_id|>ipython<|end_header_id|>\n\n" }}
        {%- if message.content is mapping or message.content is iterable %}
            {{- message.content | tojson }}
        {%- else %}
            {{- message.content }}
        {%- endif %}
        {{- eot_token }}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|start_header_id|>assistant<|end_header_id|>\n\n' }}
{%- endif %}
```

</details>

Do you have an estimation of when will a new npm package with this fix be released?
It would be useful for me to be able to use templates that uses `none`.

**Comment by xenova** [comment]
Thanks! I've published a new version with this update! 👍 https://www.npmjs.com/package/@huggingface/jinja/v/0.3.1

**Pull request merged**
