### PR TITLE
[jinja] Add support for macros and `| tojson`

### PR DESCRIPTION
**Pull request by xenova**
Adds support for Macros. See here for more information: https://jinja.palletsprojects.com/en/3.1.x/templates/#macros

cc @Rocketknight1

### CODE REVIEW

**Comment by xenova** [comment]
Example usage:
```js
import { Template } from "@huggingface/jinja";
import { downloadFile } from "@huggingface/hub";

// Download config file from the Hugging Face Hub
const config = await (
	await downloadFile({
		repo: "CohereForAI/c4ai-command-r-plus",
		path: "tokenizer_config.json",
		revision: "refs/pr/46",
	})
).json();

// Construct template from config
const template = new Template(config.chat_template.find((t) => t.name === "tool_use").template);

// Define messages and tools
const messages = [{ role: "user", content: "Whats the biggest penguin in the world?" }];
const tools = [
	{
		name: "directly_answer",
		description: "Calls a standard (un-augmented) AI chatbot to generate a response given the conversation history",
		parameters: { type: "object", properties: {} },
	},
	{
		name: "internet_search",
		description: "Returns a list of relevant document snippets for a textual query retrieved from the internet",
		parameters: {
			type: "object",
			properties: { query: { type: "string", description: "Query to search the internet with" } },
			required: ["query"],
		},
		return: { type: "string", description: "Some text" },
	},
];

// Render template
const result = template.render({
	messages,
	tools,
	bos_token: config.bos_token,
	eos_token: config.eos_token,
});
console.log(result);
```

<details>

<summary>Outputs:</summary>

````
<BOS_TOKEN><|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|># Safety Preamble
The instructions in this section override those in the task description and style guide sections. Don't answer questions that are harmful or immoral.

# System Preamble
## Basic Rules
You are a powerful conversational AI trained by Cohere to help people. You are augmented by a number of tools, and your job is to use and consume the output of these tools to best help the user. You 
will see a conversation history between yourself and a user, ending with an utterance from the user. You will then see a specific instruction instructing you what kind of response to generate. When you answer the user's requests, you cite your sources in your answers, according to those instructions.

# User Preamble
## Task and Context
You help people answer their questions and other requests interactively. You will be asked a very wide array of requests on all kinds of topics. You will be equipped with a wide range of search engines or similar tools to help you, which you use to research your answer. You should focus on serving the user's needs as best you can, which will be wide-ranging.

## Style Guide
Unless the user asks for a different style of answer, you should answer in full sentences, using proper grammar and spelling.

## Available Tools
Here is a list of tools that you have available to you:

```python
def directly_answer() -> List[Dict]:
    """Calls a standard (un-augmented) AI chatbot to generate a response given the conversation history
    """
    pass
```

```python
def internet_search(query: str) -> List[Dict]:
    """Returns a list of relevant document snippets for a textual query retrieved from the internet

    Args:
        query (str): Query to search the internet with
    """
    pass
```<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|USER_TOKEN|>Whats the biggest penguin in the world?<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>Write 'Action:' followed by a json-formatted list of actions that you want to perform in order to produce a good response to the user's last input. You can use any of the supplied tools any number of times, but you should aim to execute the minimum number of necessary actions for the input. You should use the `directly-answer` tool if calling the other tools is unnecessary. The list of actions you want to call should be formatted as 
a list of json objects, for example:
```json
[
    {
        "tool_name": title of the tool in the specification,
        "parameters": a dict of parameters to input into the tool as they are defined in the specs, or {} if it takes no parameters
    }
]```<|END_OF_TURN_TOKEN|>

````

</details>

**Comment by xenova** [comment]
Now also supports `| tojson` 👍 https://github.com/huggingface/transformers/pull/31100

**Comment by xenova** [comment]
found one: https://huggingface.co/CohereForAI/c4ai-command-r-plus/discussions/46/files

**Comment by Rocketknight1** [comment]
Yes, that works! You can also use [Mistral-7B-Instruct](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3/discussions/35) or [Hermes-2-Pro](https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B/discussions/13)

**Comment by Rocketknight1** [comment]
Also note that we currently implement `|tojson` a little differently from the Jinja standard; it actually redirects to `json.dumps()` in Python because Jinja's built-in method escapes HTML characters, and we want to avoid that.

**Comment by xenova** [comment]
Perfect! I've added tests for both those templates, and both function correctly! I think this PR is ready to merge after another look tomorrow.

**Comment by xenova** [comment]
Finally got around to adding this to Transformers.js (v3). Merging! 🚀

**Pull request merged**
