### PR TITLE
Jinja - support `rejectattr`

### PR DESCRIPTION
**Pull request by giladgd**
I've added support for `rejectattr` in Jinja since I encountered some GGUF models that include a chat template that uses it, like [this one](https://huggingface.co/mradermacher/Mistral-Nemo-Instruct-2407-GGUF) for example.

### CODE REVIEW

**Review by xenova — CHANGES_REQUESTED** [review]
Thanks for the PR! 🎉 

Since `rejectattr` is very similar to `selectattr`, maybe we can remove code redundancy by reusing the logic?

Something like:
```js
case "selectattr": 
case "rejectattr": 
{
const select = filterName === "selectattr";

// ... same logic

// Filter the array using the test function
const filtered = (operand.value as ObjectValue[]).filter((item) => {
    const a = item.value.get(attr.value);
    const result = a ? testFunction(a, value) : false;
    return select ? result : !result;
});

}
```

the following should do the same (less readable though)
```js
const filtered = (operand.value as ObjectValue[]).filter(item => {
    const a = item.value.get(attr.value);
    return select === Boolean(a && testFunction(a, value));
});
```

**Comment by giladgd** [comment]
I've made the changes, and the tests seem to pass

**Review by xenova — APPROVED** [review]
A perfect PR! Thanks a ton! ✅ 

Will put out a new release shortly too (just needing to finish one more thing)

**Comment by julien-c** [comment]
thanks for the contrib, @giladgd!

**Pull request merged**
