### PR TITLE
✏️ Fix comments that are mixed up - ImageClassificationOutputValue

### PR DESCRIPTION
**Pull request by fonzarely**

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]
Thanks!

**Comment by coyotte508** [comment]
Can you run prettier? (`pnpm -r format`)

**Comment by fonzarely** [comment]
> Can you run prettier? (`pnpm -r format`)

Yes, but it is changing files I did not update. 
I'm sending the update.

**Comment by coyotte508** [comment]
No problem, thanks a lot :)

**Pull request merged**
