### PR TITLE
Add Sanctum local app to "Use this model" list

### PR DESCRIPTION
**Pull request by pbendus**
Hi HuggingFace team!

Sanctum is a local encrypted application for running open-source LLMs in just a few clicks. It has a direct integration with HuggingFace GGUF models, so it'd be great to have it under the list of "Use this model" local apps. Sanctum is free and available for download on MacOS & Windows here: [https://sanctum.ai](https://sanctum.ai)

We've also implemented support for deep links, here's a quick video on how it works on MacOS (Windows is also supported). Feel free to use this link to try it out: `sanctum://open_from_hf?model=SanctumAI/Meta-Llama-3-8B-Instruct-GGUF`

https://github.com/huggingface/huggingface.js/assets/32494918/9f9acc09-0396-48b7-ba8b-9945c6dd547c

Also is there anything we could do for Sanctum to be available in the "Use this model" app list by default?

Thanks in advance!

### CODE REVIEW

**Comment by julien-c** [comment]
Sanctum looks cool! 

I'll DL and try it

for being in the dropdown by default we are going to transition to a more algorithmic way in the near future. So there will be no more defaults

**Comment by julien-c** [comment]
do you have a square SVG icon btw?

**Comment by pbendus** [comment]
> do you have a square SVG icon btw?

Sure thing, attaching below:

sanctum

**Review by krampstudio — APPROVED** [review]
:+1:

**Comment by pbendus** [comment]
Hey guys, is there anything else we should do here before this gets merged? Thanks!

**Review by osanseviero — APPROVED** [review]
LGTM from my side. This will need an internal PR with the icon as well, so we're coordinating between them :)

**Comment by coyotte508** [comment]
cc @krampstudio (or @enzostvs ?) for the hub side?

**Comment by krampstudio** [comment]
@pbendus this is finally released 😅 Users will be able to launch Sanctum from an HF model page. Don't hesitate to spread the news to your users

**Comment by pbendus** [comment]
Great news @krampstudio 

Thanks!

**Pull request merged**
