### PR TITLE
Add new text-to-image LocalApp JoyFusion(macOS)

### PR DESCRIPTION
**Pull request by jiangdi0924**
JoyFusion is a native application for macOS , built upon Stable Diffusion and CoreML technologies. It can locally run CoreML-based text-to-image models.

Currently, only `CoreML model ZIP file` imports are supported, but more file types will be supported in the future.
For now, you can find CoreML files in the following repos or community:
https://huggingface.co/Norton0924/Joyfusion/tree/main
https://huggingface.co/coreml-community

👇Here is  App Icon SVG
joyfusion (1)

👇Demo Video

https://github.com/huggingface/huggingface.js/assets/21988177/2db2c186-a0dc-4707-8ce5-de1e74071edb

### CODE REVIEW

**Review by enzostvs — APPROVED** [review]
works well!
> side note: to implement it through HF Hub we should add a files check, as the app works only if there is at least 1 .zip

**Comment by julien-c** [comment]
Hi @jiangdi0924, any way to support all coreml models (no zip file needed), or alternatively, do you have a tag on model repos you support? i.e. repos could specify a `joyfusion` tag in their model card to be deemed as compatible with JoyFusion?

Thanks!

**Comment by jiangdi0924** [comment]
> Hi @jiangdi0924, any way to support all coreml models (no zip file needed), or alternatively, do you have a tag on model repos you support? i.e. repos could specify a `joyfusion` tag in their model card to be deemed as compatible with JoyFusion?
> 
> Thanks!

Hello Julien-C,

Thank you for your feedback. Indeed, at the moment, we only support the zip file format for coreML models. Currently, there are a significant number of coreML model zips available on Hugging Face. We plan to support CoreML Repos with non-zip file types in the next version.

This PR has been pending for a while, and if possible, we would like to merge it and release a version. After the merge, we will continue to optimize the file types for importing models and the user experience.

Additionally, regarding your suggestion for the JoyFusion tag, there are indeed some limitations at present. Once again, thank you for your feedback.

**Comment by pcuenca** [comment]
> works well

Tested here, works fine for me too.

**Comment by enzostvs** [comment]
Hi @jiangdi0924 
Could you run the linter on your PR to format it properly please ?
You can install the `prettier` extension on VSCode, should be automatic after a save 

Thank you 🙏

**Comment by jiangdi0924** [comment]
> Hi @jiangdi0924 Could you run the linter on your PR to format it properly please ? You can install the `prettier` extension on VSCode, should be automatic after a save
> 
> Thank you 🙏
👋 @enzostvs , sorry about the formatting issues in the previous code. I’ve tried using Prettier to it and made another commit (Tag: 066a1722f55f2b71868abe6e9bcb124b67e1cbd9). If there are any problems, please let me know anytime.

**Comment by enzostvs** [comment]
Test passed, PR has been merged!
Thank you @jiangdi0924 for your contribution 🚀

**Comment by julien-c** [comment]
made a small tweak (for now) in #847 requiring an explicit `joyfusion` tag on the model

**Comment by enzostvs** [comment]
Hey @jiangdi0924 
JoyFusion has been added to HF local apps! You can see it on my screen:
Screenshot 2024-08-14 at 9 33 20 AM

You can now communicate on it if you need to !

Thanks again for your contribution!

**Comment by jiangdi0924** [comment]
> Hey @jiangdi0924 JoyFusion has been added to HF local apps! You can see it on my screen: Screenshot 2024-08-14 at 9 33 20 AM
> 
> You can now communicate on it if you need to !
> 
> Thanks again for your contribution!

Hi  @enzostvs , Thanks for the support! It’s awesome to see JoyFusion on huggingface’s Local Apps. Looking forward to our next collaboration! 🫡

**Pull request merged**
