### PR TITLE
[jinja] Add more built-in functions

### PR DESCRIPTION
**Pull request by xenova**
This PR adds support for several built-in jinja filters (from [this list](https://jinja.palletsprojects.com/en/3.0.x/templates/#list-of-builtin-filters)).

Related discussion: https://huggingface.co/codellama/CodeLlama-70b-Instruct-hf/discussions/21

cc @pcuenca @Rocketknight1

### CODE REVIEW

**Comment by xenova** [comment]
From the list [here](https://jinja.palletsprojects.com/en/3.0.x/templates/#list-of-builtin-filters), are the any other built-in filters I should include in this PR?

image

**Comment by Rocketknight1** [comment]
I was about to suggest `capitalize()`/`title()` but I see you've already got it! I think this covers all of the string methods that I've seen in chat templates.

**Review by pcuenca — APPROVED** [review]
Nice! If @Rocketknight1 is happy I'm happy :)

**Comment by drbh** [comment]
great addition! thank you!

**Pull request merged**
