### PR TITLE
feat: add GGMLFileQuantizationType and apply to test

### PR DESCRIPTION
**Pull request by snowyu**
@mishig25 that's it for #794

### CODE REVIEW

**Comment by julien-c** [comment]
cc @ngxson too

**Review by ngxson — APPROVED** [review]
LGTM. Thanks :+1:

**Review by julien-c — APPROVED** [review]
will let @mishig25 do a final review and merge 👌 

Thanks a lot @snowyu!

**Comment by ngxson** [comment]
FYI, I added the `MOSTLY_` prefix in the last commit, to better reflect the type name from ggml (see [here](https://github.com/ggerganov/llama.cpp/blob/c8ddce85606d9fb6e30745b6e4fe103eecadc73f/ggml/include/ggml.h#L412-L440))

The reason is because many operations in ggml only support F32 for 1d tensors. So in fact, gguf file is never "purely" quantized, but rather being a mix between quantized type and F32.

**Comment by julien-c** [comment]
BTW, i also propose to display the enum's key name in a tooltip inside the GGUF file viewer, like this:

image

([internal PR](https://github.com/huggingface-internal/moon-landing/pull/10943))

**Review by julien-c — APPROVED** [review]

**Comment by julien-c** [comment]
i'll let you merge @ngxson!

**Comment by snowyu** [comment]
@ngxson be careful,  the const is not in `ggml.h`, it's in [llama.h](https://github.com/ggerganov/llama.cpp/blob/7a221b672e49dfae459b1af27210ba3f2b5419b6/include/llama.h#L131).

**Comment by ngxson** [comment]
Yeah I linked to the incorrect file, but the content is not changed anyway, I only added `MOSTLY_` on top of your commit. (So everything is still correct)

**Pull request merged**
