### PR TITLE
Adds Snapdragon X Elite and X Plus GPU scores to hardware.ts

### PR DESCRIPTION
**Pull request by mrkiura**
Added:
* Snapdragon X Elite
  * X1E-00-1DE
  * X1E-84-100
  * X1E-80-100
  * X1E-78-100
  
* Snapdragon X Plus
  * X1P-64-100
 
Addresses: #764 
Source: https://www.qualcomm.com/products/mobile/snapdragon/laptops-and-tablets/snapdragon-x-elite

### CODE REVIEW

**Comment by coyotte508** [comment]
Even if it has an integrated GPU, I think maybe it belongs in CPUs?

Also what to do about NPU score @pcuenca / @julien-c ? They have 45 TOps in their NPU, and arguably the NPU is more important than the GPU for ML stuff.

**Review by Vaibhavs10 — COMMENTED** [review]
I'd consider it a GPU still - in more long-term ideally, we'd be able to use the device info they put and customise snippets and even recommend models for their tasks down the line.

Besides, down the line when NPUs are more mainstream it might make sense to add it as a separate add-on.

**Review by Vaibhavs10 — COMMENTED** [review]
Hey @mrkiura - thanks a ton for your contribution, please do make sure to run the linter so that the lint test passes.

If you use VS code then you can do so with the `prettier` extension too.

**Comment by mrkiura** [comment]
Thanks @coyotte508 @Vaibhavs10 

I have updated the branch.

**Review by coyotte508 — APPROVED** [review]

**Review by julien-c — COMMENTED** [review]
maybe of interest to @mfuntowicz too

**Comment by mrkiura** [comment]
It seems like the Test/node and (Test/ browser) checks are failing because [this URL](https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/utils/WebBlob.spec.ts#L54) in packages/hub/src/utils/WebBlob.spec.ts references a file from runway ml's account, but Runway is no longer maintaining a hugging face organization. It probably needs to be addressed in a different PR.

Cc @julien-c @coyotte508 @Vaibhavs10

**Comment by coyotte508** [comment]
> It seems like the Test/node and (Test/ browser) checks are failing because [this URL](https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/utils/WebBlob.spec.ts?rgh-link-date=2024-09-03T18%3A42%3A21Z#L54) in packages/hub/src/utils/WebBlob.spec.ts references a file from runwayml's account, but Runway is no longer maintaining a HuggingFace organization. It probably needs to be addressed in a different PR.
> 
> Cc @julien-c @coyotte508 @Vaibhavs10

yes you can ignore those tests

**Review by pcuenca — APPROVED** [review]
I tend to agree with @coyotte508, it somehow feels more natural to classify them as CPUs, but no strong opinion.

**Review by Vaibhavs10 — APPROVED** [review]
Good to merge then, we can revisit the classification when we have a bit more candidates? ✅

**Comment by Vaibhavs10** [comment]
Thanks a lot again for the contribution @mrkiura ❤️

**Pull request merged**
