### PR TITLE
Add recurrentgemma and gemma.cpp as libraries

### PR DESCRIPTION
**Pull request by osanseviero**

### CODE REVIEW

**Review by Vaibhavs10 — APPROVED** [review]
LGTM, confirmed by looking through all the repos here: https://huggingface.co/models?other=gemma.cpp

They all only seem to have `*.sbs` file format.

**Review by pcuenca — COMMENTED** [review]
LGTM

**Review by SBrandeis — APPROVED** [review]

**Review by julien-c — APPROVED** [review]
nice – should they have icons in the internal codebase?

**Review by Wauplin — COMMENTED** [review]
LGTM!

About icons, couldn't we make the process public -same as the library definitions-? Suggesting it since we have quite a lot of those, especially now that we are adding local apps as well.

**Review by Wauplin — APPROVED** [review]
LGTM!

About icons, couldn't we make the process public -same as the library definitions-? Suggesting it since we have quite a lot of those, especially now that we are adding local apps as well.

**Pull request merged**
