### PR TITLE
Update ASR task page

### PR DESCRIPTION
**Pull request by Deep-unlearning**

### CODE REVIEW

**Review by merveenoyan — COMMENTED** [review]
looks good to me, but I'd like to get @Vaibhavs10's opinion/approval
also @Vaibhavs10 should we remove sanchit-gandhi/whisper-jax from demos? this PR does that

**Review by Vaibhavs10 — APPROVED** [review]
Thanks it looks good, yes Whisper-JAX has an issue w/ TPU's atm. Need to debug/ clear cache on demand there (which is non-trivial since we don't have full access cc: @pcuenca )

Good to merge tho 👍

**Comment by Vaibhavs10** [comment]
btw @Deep-unlearning is Steven :p

**Review by pcuenca — APPROVED** [review]
Looks good to me!

**Comment by pcuenca** [comment]
> which is non-trivial since we don't have full access

We should. Let me take a look (next week) and I'll update the docs.

**Comment by julien-c** [comment]
> btw @Deep-unlearning is Steven :p

neat gh handle Steven 😆  what's your hf handle?

**Comment by Deep-unlearning** [comment]
> > btw @Deep-unlearning is Steven :p
> 
> neat gh handle Steven 😆 what's your hf handle?

ahah thanks ! my hf handle is [Steveeeeeeen](https://huggingface.co/Steveeeeeeen), less neat tho :')

**Comment by julien-c** [comment]
🤔 

image

**Comment by pcuenca** [comment]
The heart count needs to go up too :)

**Comment by Deep-unlearning** [comment]
> The heart count needs to go up too :)

Im working on it 🚀

**Pull request merged**
