### PR TITLE
Update ApiError to HubApiError

### PR DESCRIPTION
**Pull request by syedMohib44**
Change filename ApiError to HubApiError as well also updated in ApiError.md -> HubApiError.md

### CODE REVIEW

**Comment by coyotte508** [comment]
Thanks!

You don't need to change anything in the docs folder, it's automatically generated during releases

**Comment by syedMohib44** [comment]
> Thanks!
> 
> You don't need to change anything in the docs folder, it's automatically generated during releases

> Ohh alright let me revert that and recommit. Thanks :)

**Comment by coyotte508** [comment]
Still two files to revert :)

image

**Comment by syedMohib44** [comment]
> Update docs

Ohh man really update just now please review once if its correct now. Thanks for the headsup 💯 🙂

**Review by coyotte508 — APPROVED** [review]
Nice @syedMohib44 !

**Comment by syedMohib44** [comment]
> Nice @syedMohib44 !

Thanks for the help bro 👍

**Review by syedMohib44 — COMMENTED** [review]
Updated ApiError to HubApiError

**Comment by Sameyboy88** [comment]
[]()merged

**Pull request merged**
