### PR TITLE
gguf: Fix ArrayBuffer.resize not supported on Firefox

### PR DESCRIPTION
**Pull request by ngxson**
`ArrayBuffer.resize()` is not supported on Firefox. This causes the error while visualizing gguf:

image

This PR introduces a small patch that uses a polyfill in case `ArrayBuffer.resize()` cannot be used.

Tested on Firefox and Chrome.

### CODE REVIEW

**Comment by julien-c** [comment]
(though i wish they would support it soon?)

**Comment by ngxson** [comment]
According to [caniuse page](https://caniuse.com/?search=ArrayBuffer.resize), the support is experimental on version 124 (current version) of firefox (can be enabled via a flag). So I think it's expected to be stable on 125. Unfortunate I couldn't find the issue tracker anywhere so I can't confirm that information.

In any way, I feel like this API is relative new on all other browsers, so it's maybe better to keep this polyfill for a while.

**Comment by julien-c** [comment]
let's merge @mishig25 and set a reminder to remove (in a couple of weeks?) when Firefox support is fully out?

**Comment by mishig25** [comment]
Merged it. Some tests were failing citing a token issue (likely because the PR comes from a fork)

>  set a reminder to remove (in a couple of weeks?) when Firefox support is fully out?

https://github.com/huggingface/huggingface.js/issues/642

**Comment by mishig25** [comment]
@ngxson thanks a lot for the contribution! I've tweeted about it [here](https://twitter.com/mishig25/status/1784945423104245763)

**Comment by ngxson** [comment]
> @ngxson thanks a lot for the contribution! I've tweeted about it [here](https://twitter.com/mishig25/status/1784945423104245763)

Thanks! Great to see that it works on Firefox now :smile: 

Btw my twitter is also @ngxson

**Pull request merged**
