### PR TITLE
Amend spec for token classification

### PR DESCRIPTION
**Pull request by Rocketknight1**
This PR makes a few changes to the spec for `token-classification` output:

1) We allow either `entity` or `entity_group`. In `transformers`, `entity` is used for standard token classification or NER when we don't aggregate tokens, and `entity_group` is used when a single label is applied to an aggregated group of tokens.
2) We remove `label` from the `required` list. `label` was not actually one of the output keys in the spec, or in `transformers`!
3) We add `start`, `end` and `word` to the required list.

### CODE REVIEW

**Review by Wauplin — COMMENTED** [review]
Looks good to me! Thanks for updating these. 
Let's wait for a second review before merging :)

**Review by Wauplin — APPROVED** [review]
Looks good to me! Thanks for updating these. 
Let's wait for a second review before merging :)

**Comment by Wauplin** [comment]
(I just pushed https://github.com/huggingface/huggingface.js/pull/969/commits/d68a9b3fb6476d495bf3d236046a47ffe43cee78 to fix the test)

**Comment by Rocketknight1** [comment]
Ah, got it! Didn't realize the comments had to match too.

**Comment by Wauplin** [comment]
It is auto-generated by running

```
(cd packages/tasks && pnpm run inference-codegen)
```

**Comment by SBrandeis** [comment]
> We allow either entity or entity_group. In transformers, entity is used for standard token classification or NER when we don't aggregate tokens, and entity_group is used when a single label is applied to an aggregated group of tokens.

Out of curiosity, why the need for a separate parameter?

**Review by julien-c — APPROVED** [review]

**Comment by Rocketknight1** [comment]
@SBrandeis it isn't strictly necessary, but the `transformers` pipeline does it to distinguish between classifications of single tokens, versus classifications of groups of tokens. We could consider changing it to comply with the spec, instead of vice-versa, but it might break some users' workflows.

**Comment by Rocketknight1** [comment]
Also @Wauplin do you know why the e2e tests are failing? Is that a blocker, or is the PR okay to merge as-is?

**Comment by Rocketknight1** [comment]
Merging, in that case!

**Pull request merged**
