### PR TITLE
✨ Add custom fetch for inference

### PR DESCRIPTION
**Pull request by coyotte508**
Part of #155

### CODE REVIEW

**Comment by syedMohib44** [comment]
Hey @coyotte508 is this issue fixed?

**Comment by coyotte508** [comment]
This PR fixes the issue for the `@huggingface/inference` module, not the `@huggingface/hub` one.

Do you need this for your project?

**Comment by syedMohib44** [comment]
> This PR fixes the issue for the `@huggingface/inference` module, not the `@huggingface/hub` one.
> 
> Do you need this for your project?

No actually I was working on it 😅 no worries if you're on it.

**Comment by syedMohib44** [comment]
> Well I'm only doing it for the `@huggingface/inference` for now, and the PR is ready. Feel free to work on the PR for `@huggingface/hub` :)

Alright I am on it then  👍   Thanks 🙂

**Pull request merged**
