### PR TITLE
Add support for KerasNLP library

### PR DESCRIPTION
**Pull request by Wauplin**
Following recent work to integrate KerasNLP library with the Hub, let's add it in our libraries list. KerasNLP is based on Keras3 but for now let's focus on the KerasNLP side of things (we also have on-going work for Keras but that's orthogonal).

This PR will add a pretty name for "KerasNLP" tag + add urls to official docs and github repo. 
We will be able to generate code snippet in the future as well but [it should be clarified](https://github.com/keras-team/keras-nlp/issues/1529#issuecomment-2040722487) first. I suggest that we merge this PR "as-is" and add support for code snippets later when it's ready. 

About download counts, KerasNLP uses a `config.json` file so it should already count correctly. 

Bonus: first KerasNLP models on the Hub? https://huggingface.co/google/gemma-2b-it-keras/discussions/2. Model can be loaded with:
```py
import keras_nlp

gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset("hf://google/gemma-2b-it-keras")
```
:tada:

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
on the [linked repo](https://huggingface.co/google/gemma-2b-it-keras/discussions/2/files) you use `keras_nlp` (with an underscore) as a tag, here you use a dash, which is it?

**Comment by julien-c** [comment]
preference for the dash on my side, would be more consistent with other libraries and look nicer

**Comment by Wauplin** [comment]
Preference for the dash as well `keras-nlp`. Will update the linked repo

**Review by osanseviero — APPROVED** [review]
LGTM, thanks!

**Review by julien-c — APPROVED** [review]

**Comment by Wauplin** [comment]
Thanks for fixing the CI @coyotte508!

**Pull request merged**
