### PR TITLE
Update code snippets to use Transformers.js v3 🎉 

### PR DESCRIPTION
**Pull request by xenova**
Transformers.js v3 is out, and is now under the HF org on NPM (`@huggingface/transformers` instead of `@xenova/transformers`). The GitHub repo has also been updated from https://github.com/xenova/transformers.js to https://github.com/huggingface/transformers.js.

This PR updates the code relevant snippets and links.

### CODE REVIEW

**Comment by xenova** [comment]
Failing tests unrelated to this PR (pickle/code scanning)

**Review by pcuenca — APPROVED** [review]
🔥

**Review by julien-c — APPROVED** [review]
🔥 🔥

**Review by gary149 — APPROVED** [review]
🚀

**Review by Wauplin — APPROVED** [review]
:fire: :fire: :fire:

**Pull request merged**
